#!/bin/zsh
source ~/.scripts/functions/compilepackagefunctions

# Check for package name
if [[ $# -eq 0 ]]; then
  # Exit if not present
  echo "${RED}==>${WHITE} You must specify a package${COLRESET}"
  return 1
fi

if [[ $1 == "-n" ]]; then
  getsources $2 get
elif [[ $1 == "-s" ]]; then
  getfiles $2 get
  multibuild
  postbuild
else
  getsources $1
  multibuild $1
  postbuild
fi
