#!/bin/zsh
source functions/compilepackagefunctions

_build="normalbuild"

[[ $(basename $0) == "compilemultipackage" ]] && _build="multibuild"

# Check for package name
if [[ $# -eq 0 ]]; then
  # Exit if not present
  echo "${RED}==>${WHITE} You must specify a package${COLRESET}"
  return 1
fi

if [[ $1 == "-n" ]]; then
  getsources $2 skip
  $_build $2
  postbuild
elif [[ $1 == "-s" ]]; then
  getfiles $2
  $_build $2
  postbuild
else
  getsources $1
  $_build $1
  postbuild
fi
