#!/bin/zsh
source ~/.scripts/functions/compilepackagefunctions

# Check for package name
if [[ $# -eq 0 ]]; then
  # Exit if not present
  echo "${RED}==>${WHITE} You must specify a package${COLRESET}"
  return 1
fi

if [[ $1 == "-n" ]]; then
  getsources $2 skip
  normalbuild $2
  postbuild
elif [[ $1 == "-s" ]]; then
  getfiles $2
  normalbuild $2
  postbuild
else
  getsources $1
  normalbuild $1
  postbuild
fi
